[alembic]
script_location = app/migrations
sqlalchemy.url = postgresql+psycopg://postgres:[YOUR_SUPABASE_DB_PASSWORD]@db.[YOUR_SUPABASE_PROJECT_REF].supabase.co:5432/postgres

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
