from app.schemas.crop import CropRecord


SEED_CROPS: list[CropRecord] = [
    CropRecord(
        id="maize",
        name="Maize",
        growth_days=95,
        min_rainfall_mm=150.0,
        max_rainfall_mm=260.0,
        min_temp_c=20.0,
        max_temp_c=32.0,
        planting_months=[3, 4, 5, 9, 10, 11],
        min_budget_per_m2=1.8,
        drought_sensitive=False,
        flood_sensitive=True,
        enabled=True,
    ),
    CropRecord(
        id="chili",
        name="Chili",
        growth_days=110,
        min_rainfall_mm=120.0,
        max_rainfall_mm=220.0,
        min_temp_c=21.0,
        max_temp_c=30.0,
        planting_months=[1, 2, 3, 7, 8, 9],
        min_budget_per_m2=2.8,
        drought_sensitive=True,
        flood_sensitive=True,
        enabled=True,
    ),
    CropRecord(
        id="okra",
        name="Okra",
        growth_days=55,
        min_rainfall_mm=100.0,
        max_rainfall_mm=190.0,
        min_temp_c=22.0,
        max_temp_c=34.0,
        planting_months=[2, 3, 4, 8, 9, 10],
        min_budget_per_m2=1.5,
        drought_sensitive=False,
        flood_sensitive=False,
        enabled=True,
    ),
    CropRecord(
        id="eggplant",
        name="Eggplant",
        growth_days=105,
        min_rainfall_mm=140.0,
        max_rainfall_mm=240.0,
        min_temp_c=20.0,
        max_temp_c=31.0,
        planting_months=[1, 2, 3, 9, 10, 11],
        min_budget_per_m2=2.4,
        drought_sensitive=False,
        flood_sensitive=True,
        enabled=True,
    ),
    CropRecord(
        id="cucumber",
        name="Cucumber",
        growth_days=50,
        min_rainfall_mm=120.0,
        max_rainfall_mm=200.0,
        min_temp_c=20.0,
        max_temp_c=32.0,
        planting_months=[1, 2, 3, 4, 9, 10, 11],
        min_budget_per_m2=1.9,
        drought_sensitive=True,
        flood_sensitive=False,
        enabled=True,
    ),
    CropRecord(
        id="spinach",
        name="Spinach",
        growth_days=35,
        min_rainfall_mm=100.0,
        max_rainfall_mm=180.0,
        min_temp_c=18.0,
        max_temp_c=28.0,
        planting_months=[1, 2, 3, 4, 10, 11, 12],
        min_budget_per_m2=1.3,
        drought_sensitive=True,
        flood_sensitive=False,
        enabled=True,
    ),
    CropRecord(
        id="kangkung",
        name="Kangkung",
        growth_days=30,
        min_rainfall_mm=150.0,
        max_rainfall_mm=280.0,
        min_temp_c=22.0,
        max_temp_c=34.0,
        planting_months=[1, 2, 3, 4, 5, 9, 10, 11],
        min_budget_per_m2=1.1,
        drought_sensitive=False,
        flood_sensitive=False,
        enabled=True,
    ),
    CropRecord(
        id="tomato",
        name="Tomato",
        growth_days=80,
        min_rainfall_mm=110.0,
        max_rainfall_mm=210.0,
        min_temp_c=20.0,
        max_temp_c=30.0,
        planting_months=[1, 2, 3, 4, 8, 9, 10, 11],
        min_budget_per_m2=2.2,
        drought_sensitive=True,
        flood_sensitive=True,
        enabled=True,
    ),
    CropRecord(
        id="long_bean",
        name="Long Bean",
        growth_days=60,
        min_rainfall_mm=130.0,
        max_rainfall_mm=220.0,
        min_temp_c=21.0,
        max_temp_c=32.0,
        planting_months=[2, 3, 4, 8, 9, 10],
        min_budget_per_m2=1.6,
        drought_sensitive=False,
        flood_sensitive=False,
        enabled=True,
    ),
]
